# encoding: utf-8
require 'rake'

require 'jeweler'
Jeweler::Tasks.new do |gem|
  # gem is a Gem::Specification... see http://docs.rubygems.org/read/chapter/20 for more options
  gem.name = "pubnub-ruby"
  gem.homepage = "http://github.com/pubnub/pubnub-api/tree/master/ruby"
  gem.license = "MIT"
  gem.summary = %Q{PubNub unofficial gem}
  gem.description = %Q{Simply Pubnub.rb in gem format, require "pubnub"} 
  gem.email = "stephen@pubnub.com"
  gem.authors = ["Stephen Blum"]
  gem.files = FileList['lib/**/*.rb', 'examples/**/*.rb', 'tests/**/*.rb'] 
  # dependencies defined in Gemfile
  gem.add_dependency "json"
end
Jeweler::RubygemsDotOrgTasks.new
