#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("Andr.Unit.Resource", IsApplication=true)]

namespace Andr.Unit
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues ();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int monoandroidsplash = 2130837505;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060002
			public const int dialog_BoolField = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int dialog_Button = 2131099651;
			
			// aapt resource value: 0x7f060000
			public const int dialog_LabelField = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int dialog_LabelSubtextField = 2131099649;
			
			// aapt resource value: 0x7f060005
			public const int dialog_Panel = 2131099653;
			
			// aapt resource value: 0x7f060006
			public const int dialog_RadioButtonList = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int dialog_Spinner = 2131099655;
			
			// aapt resource value: 0x7f060004
			public const int dialog_ValueField = 2131099652;
			
			// aapt resource value: 0x7f060008
			public const int iFormFieldValue = 2131099656;
			
			// aapt resource value: 0x7f060009
			public const int myButton = 2131099657;
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int dialog_achievements = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int dialog_boolfieldleft = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int dialog_boolfieldright = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int dialog_boolfieldsubleft = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int dialog_boolfieldsubright = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int dialog_button = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int dialog_datefield = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int dialog_fieldsetlabel = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int dialog_labelfieldbelow = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int dialog_labelfieldright = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int dialog_onofffieldright = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int dialog_panel = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int dialog_selectlist = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int dialog_selectlistfield = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int dialog_textarea = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int dialog_textfieldbelow = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int dialog_textfieldright = 2130903056;
			
			// aapt resource value: 0x7f030011
			public const int Main = 2130903057;
			
			// aapt resource value: 0x7f030012
			public const int monoandroidsplash = 2130903058;
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int hello = 2130968576;
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int Mono_Android_Theme_Splash = 2131034112;
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
