#!/bin/bash
 
FAILURE=1
SUCCESS=0

# Set APP_HOME to PUBNUB_GIT_ROOT/java
APP_HOME=/pubnub-api/java/3.3

LIB=${APP_HOME}/lib/
CP=${LIB}async-http-client-1.6.5-shaded.jar:${LIB}slf4j-nop-1.6.2.jar:src/:.

# cleaning up
if [ -f "$APP_HOME/src/pubnub/example/PubnubExample.java" ]; then
    echo -e "Cleaning up..."
    rm src/pubnub/example/PubnubExample/*.class
fi


# Check to see if we look good...

if [ -z "$JAVA_HOME" ]; then
    echo "Need to set JAVA_HOME environmental variable."
    exit 1
fi  

 
if [ ! -f "$JAVA_HOME/bin/javac" ]; then
    echo "Can't find javac in JAVA_HOME/bin."
    exit 1
fi

if [ ! -f "$APP_HOME/src/pubnub/example/PubnubExample.java" ]; then
    echo "Please edit this build script and verify APP_HOME is valid."
    exit 1
fi

cd ${APP_HOME}
echo -e "Building..."

${JAVA_HOME}/bin/javac -cp "${CP}" src/pubnub/example/PubnubExample.java

if [ $? -ne 0 ]
then
    echo "Test failed during compilation"
    exit ${FAILURE}
fi

echo -e "Build succeeded."
echo 
echo -e "Running..."
${JAVA_HOME}/bin/java -cp "${CP}" src/pubnub/example/PubnubExample

if [ $? -ne 0 ]
then
    echo "Tests failed."
    exit ${FAILURE}
fi

echo "Tests ran successfully!"
exit ${SUCCESS}
