#!/bin/bash
 
FAILURE=1
SUCCESS=0
 
APP_HOME=/your/app/home/path/pubnub-java/
LIB=${APP_HOME}/lib/
 
CP=${LIB}async-http-client-1.6.5-shaded.jar:${LIB}slf4j-nop-1.6.2.jar:src/:.
 
APP_JAVA_HOME=/opt/jdk
cd ${APP_HOME}
echo -e "Building..."

${APP_JAVA_HOME}/bin/javac -cp "${CP}" src/tests/PubnubUnitTest.java

if [ $? -ne 0 ]
then
    echo "Test failed during compilation"
    exit ${FAILURE}
fi
 
echo -e "Running..."
${APP_JAVA_HOME}/bin/java -cp "${CP}" src/tests/PubnubUnitTest

if [ $? -ne 0 ]
then
    echo "Test failed during run"
    exit ${FAILURE}
fi

echo "Test run successfully"
exit ${SUCCESS}