source 'https://rubygems.org'

gem 'rails', '3.2.6'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'

gem 'sqlite3'

#gem 'eventmachine', "~> 0.12.9"
gem 'em-http-request'
gem "uuid", "~> 2.3.5"
gem 'yajl-ruby'
gem 'pubnub', "3.3.0.5"
gem 'linecache19'
gem 'ruby_core_source'
gem 'ruby-debug19'
gem 'ruby-debug-base19'
gem 'httparty'
gem 'passenger'


# Gems used only for assets and not required
# in production environments by default.
group :assets do
  #gem 'sass-rails',   '~> 3.2.3'
  #gem 'coffee-rails', '~> 3.2.1'

  # See https://github.com/sstephenson/execjs#readme for more supported runtimes
#gem 'therubyracer', :platforms => :ruby

  #gem 'uglifier', '>= 1.0.3'
end

group :test do
  gem 'rspec-rails', "~> 2.0"
  gem 'ruby-debug-base19'
  gem 'rr', "1.0.4"
  gem 'vcr', "2.2.4"
  gem 'webmock', "1.8.8"
end

#gem 'jquery-rails'

# To use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.0.0'

# To use Jbuilder templates for JSON
# gem 'jbuilder'

# Use unicorn as the app server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano'

# To use debugger
# gem 'debugger'
