//
//  PNChannelEvents+Protected.h
//  pubnub
//
//  Created by Sergey Mamontov on 01/15/13.
//
//

#import "PNChannelEvents.h"


#pragma mark Protected interface methods

@interface PNChannelEvents (Protected)


#pragma mark - Properties

// Stores list of events which occurred on channel
// (presence events and message from other channel
// participants)
@property (nonatomic, strong) NSArray *events;

// Stores reference on event set occurrence time token
// which generated by PubNub service
@property (nonatomic, strong) NSNumber *timeToken;

#pragma mark -


@end
