//
//  PNChannelEvents.h
// 
//
//  Created by moonlight on 1/15/13.
//
//


#import <Foundation/Foundation.h>


@interface PNChannelEvents : NSObject


#pragma mark Properties

// Stores list of events which occurred on channel
// (presence events and message from other channel
// participants)
@property (nonatomic, readonly, strong) NSArray *events;

// Stores reference on event set occurrence time token
// which generated by PubNub service
@property (nonatomic, readonly, strong) NSNumber *timeToken;

#pragma mark -


@end