//
//  PNOperationStatus+Protected.h
//  pubnub
//
//  Created by Sergey Mamontov on 01/15/13.
//
//

#import "PNOperationStatus.h"


#pragma mark Protected interface methods

@interface PNOperationStatus (Protected)

#pragma mark - Properties

@property (nonatomic, getter = isSuccessful) BOOL successful;

// Stores error description in case of error
@property (nonatomic, strong) PNError *error;

// Stores message which arrived from PubNub service as operation
// processing status description
@property (nonatomic, copy) NSString *statusDescription;

// Stores reference on time token at which this operation status
// message was generated by PubNub service
@property (nonatomic, strong) NSNumber *timeToken;

#pragma mark -


@end
