#!/bin/bash

clang \
    -o example \
    example.m \
    pubnub.m \
    request.m \
    JSON/SBJsonParser.m \
    JSON/SBJsonStreamParserAdapter.m \
    JSON/SBJsonStreamParser.m \
    JSON/SBJsonStreamParserState.m \
    JSON/SBJsonStreamWriter.m \
    JSON/SBJsonStreamWriterState.m \
    JSON/SBJsonTokeniser.m \
    JSON/SBJsonWriter.m \
    -framework Foundation \
    -fobjc-nonfragile-abi2 \
    -Wall \
    -Wimplicit-function-declaration \
    -fstack-protector \
    -fblocks \
    -m686 \
    -lpthread \
    -lm \
    -lc \
    -lobjc

