// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Linkword
{
	
	
	public partial class Resource
	{
		
		public partial class Attribute
		{
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int audiooff = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int audioon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int dialog_disclosure = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int dialog_expander_ic_minimized = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int icon = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int splash = 2130837509;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f06000a
			public const int dialog_AnswerField = 2131099658;
			
			// aapt resource value: 0x7f060002
			public const int dialog_BoolField = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int dialog_Button = 2131099651;
			
			// aapt resource value: 0x7f060009
			public const int dialog_DisclosureField = 2131099657;
			
			// aapt resource value: 0x7f060005
			public const int dialog_ImageLeft = 2131099653;
			
			// aapt resource value: 0x7f060007
			public const int dialog_ImageRight = 2131099655;
			
			// aapt resource value: 0x7f060000
			public const int dialog_LabelField = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int dialog_LabelSubtextField = 2131099649;
			
			// aapt resource value: 0x7f06000b
			public const int dialog_Panel = 2131099659;
			
			// aapt resource value: 0x7f06000c
			public const int dialog_RadioButtonList = 2131099660;
			
			// aapt resource value: 0x7f060006
			public const int dialog_SliderField = 2131099654;
			
			// aapt resource value: 0x7f06000d
			public const int dialog_Spinner = 2131099661;
			
			// aapt resource value: 0x7f060004
			public const int dialog_ValueField = 2131099652;
			
			// aapt resource value: 0x7f06000e
			public const int iFormFieldValue = 2131099662;
			
			// aapt resource value: 0x7f060008
			public const int textView1 = 2131099656;
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int dialog_achievements = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int dialog_boolfieldleft = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int dialog_boolfieldright = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int dialog_boolfieldsubleft = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int dialog_boolfieldsubright = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int dialog_button = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int dialog_datefield = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int dialog_fieldsetlabel = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int dialog_floatimage = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int dialog_labelfieldbelow = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int dialog_labelfieldright = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int dialog_linkword_audio_next_exit = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int dialog_linkword_button = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int dialog_linkword_horizontal_label_button = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int dialog_linkword_multiline_centered_label = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int dialog_linkword_multiline_left_justified_label = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int dialog_linkword_root = 2130903056;
			
			// aapt resource value: 0x7f030011
			public const int dialog_linkword_textview_centered = 2130903057;
			
			// aapt resource value: 0x7f030012
			public const int dialog_linkword_three_horizontal_labels = 2130903058;
			
			// aapt resource value: 0x7f030013
			public const int dialog_multilinetextfield = 2130903059;
			
			// aapt resource value: 0x7f030014
			public const int dialog_onofffieldright = 2130903060;
			
			// aapt resource value: 0x7f030015
			public const int dialog_panel = 2130903061;
			
			// aapt resource value: 0x7f030016
			public const int dialog_root = 2130903062;
			
			// aapt resource value: 0x7f030017
			public const int dialog_selectlist = 2130903063;
			
			// aapt resource value: 0x7f030018
			public const int dialog_selectlistfield = 2130903064;
			
			// aapt resource value: 0x7f030019
			public const int dialog_textarea = 2130903065;
			
			// aapt resource value: 0x7f03001a
			public const int dialog_textfieldbelow = 2130903066;
			
			// aapt resource value: 0x7f03001b
			public const int dialog_textfieldleft = 2130903067;
			
			// aapt resource value: 0x7f03001c
			public const int dialog_textfieldright = 2130903068;
			
			// aapt resource value: 0x7f03001d
			public const int main = 2130903069;
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int hello = 2130968576;
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050001
			public const int Theme_Linkword = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Theme_Splash = 2131034112;
			
			private Style()
			{
			}
		}
	}
}
