#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("PubNubMessaging.Core.Resource", IsApplication=true)]

namespace PubNubMessaging.Core
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues ();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int monoandroidsplash = 2130837505;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060007
			public const int btnCancel = 2131099655;
			
			// aapt resource value: 0x7f06000b
			public const int btnDetailedHis = 2131099659;
			
			// aapt resource value: 0x7f06000c
			public const int btnHereNow = 2131099660;
			
			// aapt resource value: 0x7f060006
			public const int btnLaunch = 2131099654;
			
			// aapt resource value: 0x7f06000a
			public const int btnPresence = 2131099658;
			
			// aapt resource value: 0x7f060005
			public const int btnProxy = 2131099653;
			
			// aapt resource value: 0x7f060018
			public const int btnProxyCancel = 2131099672;
			
			// aapt resource value: 0x7f060017
			public const int btnProxySave = 2131099671;
			
			// aapt resource value: 0x7f060009
			public const int btnPublish = 2131099657;
			
			// aapt resource value: 0x7f060008
			public const int btnSubscribe = 2131099656;
			
			// aapt resource value: 0x7f06000d
			public const int btnTime = 2131099661;
			
			// aapt resource value: 0x7f06000e
			public const int btnUnsub = 2131099662;
			
			// aapt resource value: 0x7f06000f
			public const int btnUnsubPres = 2131099663;
			
			// aapt resource value: 0x7f060016
			public const int proxyPassword = 2131099670;
			
			// aapt resource value: 0x7f060014
			public const int proxyPort = 2131099668;
			
			// aapt resource value: 0x7f060013
			public const int proxyServer = 2131099667;
			
			// aapt resource value: 0x7f060015
			public const int proxyUsername = 2131099669;
			
			// aapt resource value: 0x7f060010
			public const int scroll = 2131099664;
			
			// aapt resource value: 0x7f060012
			public const int tbProxy = 2131099666;
			
			// aapt resource value: 0x7f060001
			public const int tbSsl = 2131099649;
			
			// aapt resource value: 0x7f060004
			public const int tvProxy = 2131099652;
			
			// aapt resource value: 0x7f060000
			public const int txtChannel = 2131099648;
			
			// aapt resource value: 0x7f060002
			public const int txtCipher = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int txtCustomUuid = 2131099651;
			
			// aapt resource value: 0x7f060011
			public const int txtViewLog = 2131099665;
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Launch = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int monoandroidsplash = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Proxy = 2130903043;
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f04001c
			public const int app_name = 2130968604;
			
			// aapt resource value: 0x7f04000c
			public const int cancel = 2130968588;
			
			// aapt resource value: 0x7f040016
			public const int channel = 2130968598;
			
			// aapt resource value: 0x7f04001a
			public const int cipher = 2130968602;
			
			// aapt resource value: 0x7f040000
			public const int customUuid = 2130968576;
			
			// aapt resource value: 0x7f040012
			public const int detailedHistory = 2130968594;
			
			// aapt resource value: 0x7f040001
			public const int enableproxy = 2130968577;
			
			// aapt resource value: 0x7f040017
			public const int enablessl = 2130968599;
			
			// aapt resource value: 0x7f040011
			public const int herenow = 2130968593;
			
			// aapt resource value: 0x7f04001b
			public const int launch = 2130968603;
			
			// aapt resource value: 0x7f040010
			public const int presence = 2130968592;
			
			// aapt resource value: 0x7f040002
			public const int proxy = 2130968578;
			
			// aapt resource value: 0x7f04000b
			public const int proxyCancel = 2130968587;
			
			// aapt resource value: 0x7f040005
			public const int proxyOff = 2130968581;
			
			// aapt resource value: 0x7f040004
			public const int proxyOn = 2130968580;
			
			// aapt resource value: 0x7f040009
			public const int proxyPassword = 2130968585;
			
			// aapt resource value: 0x7f040007
			public const int proxyPort = 2130968583;
			
			// aapt resource value: 0x7f04000a
			public const int proxySave = 2130968586;
			
			// aapt resource value: 0x7f040006
			public const int proxyServer = 2130968582;
			
			// aapt resource value: 0x7f040008
			public const int proxyUsername = 2130968584;
			
			// aapt resource value: 0x7f04000f
			public const int publish = 2130968591;
			
			// aapt resource value: 0x7f040003
			public const int setProxy = 2130968579;
			
			// aapt resource value: 0x7f040019
			public const int sslOff = 2130968601;
			
			// aapt resource value: 0x7f040018
			public const int sslOn = 2130968600;
			
			// aapt resource value: 0x7f04000d
			public const int subscribe = 2130968589;
			
			// aapt resource value: 0x7f04000e
			public const int subscribeConnCallback = 2130968590;
			
			// aapt resource value: 0x7f040013
			public const int time = 2130968595;
			
			// aapt resource value: 0x7f040014
			public const int unsubscribe = 2130968596;
			
			// aapt resource value: 0x7f040015
			public const int unsubscribePres = 2130968597;
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int Mono_Android_Theme_Splash = 2131034112;
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
