#!/bin/bash

echo -e "Building..."
#gmcs -debug Pubnub.cs -r:/usr/lib/mono/2.0/System.Web.Extensions.dll
gmcs -debug PubnubCustomer.cs -r:System.Web.Extensions.dll

echo -e "Running:"
mono --debug PubnubCustomer.exe
