# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{pubnub}
  s.version = "0.1.12"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Luke Carpenter / PubNub.com"]
  s.date = %q{2012-06-20}
  s.description = %q{Simply Pubnub.rb in gem format, :require => "pubnub" - ask @PubNub for upgrades.}
  s.email = %q{stephen@pubnub.com}
  s.extra_rdoc_files = ["README"]
  s.files = [
    "examples/history_example.rb",
    "examples/publish_example.rb",
    "examples/subscribe_example.rb",
    "examples/uuid_example.rb",
    "lib/pubnub.rb",
    "lib/pubnub_crypto.rb",
    "tests/unit_test.rb"
  ]
  s.homepage = %q{http://github.com/pubnub/pubnub-api}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.7.2}
  s.summary = %q{PubNub Official GEM}

  if s.respond_to? :specification_version then
    s.specification_version = 3
    s.add_dependency "em-http-request", ">= 1.0.2"
	
    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<json>, [">= 0"])
    else
      s.add_dependency(%q<json>, [">= 0"])
    end
  else
    s.add_dependency(%q<json>, [">= 0"])
  end
end
